### ISSUE TITLE
Read.eof_seen

### ISSUE THREAD

**Issue by talex5** [cdaringe/protohacks#2]
Hi, just glancing through the code after you posted on discuss (always interesting to see how people are using Eio!). I noticed you're doing:

```ocaml
let read_lines_exn ~buf ~on_line =
  while Read.eof_seen buf = false do
    on_line (Read.line buf);
    Fiber.yield ()
  done;
  ()
```

I suspect `eof_seen` isn't what you want, since there can still be lines in the buffer that need to be processed even after the underlying flow has reported end-of-file, or you may already be at the end without yet knowing it. You probably want to use `at_end_of_input` instead (or just wait for `End_of_file`, or use `Buf_read.lines`).

**Comment by cdaringe** [comment]
wow, it's staggering that it worked at all! 🤷 Thanks for the ping, i really appreciate it!

fixed in a721f43
